name = "d1-starter-sessions-api"
main = "src/index.ts"
compatibility_date = "2025-03-17"
compatibility_flags = ["nodejs_compat"]
account_id = "d1416265449d2a0bae41c45c791270ec"

# Observability
[observability]
enabled = true

# Assets
[assets]
directory = "./public/"

# KV namespace for storing sync state and tokens
[[kv_namespaces]]
binding = "SYNC_STATE"
id = "e3c00f1508eb40839e312defdbc0b696"
preview_id = "c494a513826048dfb8c4d50fce4f6242"

# Hyperdrive binding - replace with your actual Hyperdrive ID
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "e9bedbd4ce61453da32030c8333e1f25" # supabase-ns


# Cron trigger for automatic syncing every hour
[triggers]
crons = ["0 * * * *"]

# D1 database (matching wrangler.jsonc)
[[d1_databases]]
binding = "DB01"
database_name = "d1-starter-sessions-api"
database_id = "4c70d7eb-d173-4396-b11b-6bbb971eaac7"

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "246a76714a2a49d5852dd7831dd6d731"

[vars]
KEAP_APP_ID = "f3758888-5b87-4228-b394-669991d857f8"
KEAP_CLIENT_ID = "q97htu3Rn9eW0tSPh5WNIWeN5bUVn57sIWiAZctwx3O8kov6"
WORKER_AUTH_TOKEN = "GqmS3WJHA69Prddovzvrjmpf_IZ1kfkFrS9SrNIz"
SUPABASE_URL = "https://ulyrnuemxucoglbcwzig.supabase.co"

